import './globals.css'
import type { Metadata } from 'next'
import NextAuthSessionProvider from "./sessionprovider/SessionProvider";
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Feedback For Websites',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
           <body className={inter.className}><NextAuthSessionProvider>{children}</NextAuthSessionProvider></body>
    </html>
  )
}
